spring.application.name=book-review

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Book-review
spring.datasource.username=postgres
spring.datasource.password=18052004

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080